name: PR Checks
on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/**'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: '9.0.0'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Linting for changed apps
        run: pnpm lint --affected

      # - name: Run Tests for changed apps
      #   if: steps.changed-dirs.outputs.dirs != ''
      #   run: |
      #     for dir in ${{ steps.changed-dirs.outputs.dirs }}; do
      #       echo "Testing apps/$dir"
      #       pnpm test --filter $dir
      #     done
