name: Preview Build
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'apps/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: '9.0.0'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Debug Environment
        run: |
          echo "TURBO_TEAM is set: ${{ secrets.TURBO_TEAM != '' }}"
          echo "TURBO_TOKEN length: ${#TURBO_TOKEN}"
          echo "Current working directory: $(pwd)"
          echo "Files in current directory: $(ls -la)"

      - name: Build affected apps
        run: pnpm build --filter=[HEAD^1]
        env:
          TURBO_REMOTE_ONLY: 'true'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.TURBO_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --token=${{ secrets.TURBO_TOKEN }}
