name: Main Branch Build

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: '9.0.0'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build all apps
        run: pnpm build
        env:
          TURBO_REMOTE_ONLY: 'true'

      - name: Deploy to Prod
        uses: vercel/vercel-action@v2
        with:
          vercel-token: ${{ secrets.TURBO_TOKEN }}
          vercel-args: '--prod'
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
