name: Main Branch Build
on:
  push:
    branches: [main]
    paths:
      - 'apps/**'

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed for turborepo to detect changes

      - uses: pnpm/action-setup@v3
        with:
          version: '9.0.0'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build affected apps
        # run: pnpm build --filter=[HEAD^1]
        run: pnpm build --affected
